POST http://localhost:3001/api/notes
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV0a2Fyc2giLCJpZCI6IjYzM2M2MDE3OWM2YjgxZjU1MzZhYTlkNiIsImlhdCI6MTY2NDkwMTE2Nn0.gpatD3ex_Tcdkcfq_nHm0329730gKFLNtTdYwY75i1o

{
    "content": "This is utkarsh first note",
    "important": true
}